const releaseBuild = process.env.OPENVZ_RELEASE_BUILD === '1'

function azureSignOptions() {
  const values = {
    publisherName: process.env.OPENVZ_AZURE_PUBLISHER,
    endpoint: process.env.OPENVZ_AZURE_ENDPOINT,
    certificateProfileName: process.env.OPENVZ_AZURE_CERTIFICATE_PROFILE,
    codeSigningAccountName: process.env.OPENVZ_AZURE_ACCOUNT_NAME,
  }
  return Object.values(values).every(Boolean) ? values : undefined
}

module.exports = {
  appId: 'com.openvz.agent',
  productName: 'OpenVZ Agent',
  npmRebuild: false,
  asar: { smartUnpack: false },
  asarUnpack: [
    '**/node_modules/better-sqlite3/build/Release/*.node',
    '**/node_modules/better-sqlite3/prebuilds/*.node',
    '**/node_modules/@huggingface/transformers/**',
    '**/node_modules/sharp/**',
    '**/node_modules/@img/sharp-*/**',
    '**/node_modules/onnxruntime-node/**',
    '**/node_modules/sherpa-onnx-node/**',
    '**/node_modules/sherpa-onnx-win-x64/**',
    '**/node_modules/sherpa-onnx-darwin-x64/**',
    '**/node_modules/sherpa-onnx-darwin-arm64/**',
    'build/native-speech-recognizer',
    'src/voice/**',
    'src/mcp/servers/**',
  ],
  extraResources: [
    {
      from: 'build/playwright-browsers/${os}-${arch}',
      to: 'playwright-browsers',
      filter: ['**/*'],
    },
  ],
  files: [
    'electron/**/*',
    'src/**/*',
    'skills/**/*',
    'scripts/seed-memories.js',
    'index.html',
    'dashboard.html',
    'brain.html',
    'brain-ui.html',
    'website.html',
    'systemPrompt.html',
    'activation.html',
    'focus-banner.html',
    'turn-trace.html',
    'SCENE-PROTOCOL.md',
    'UPSTREAM-SYNC.md',
    'build/icon.ico',
    'build/icon.icns',
    'build/icon.png',
    'build/icon-mac-cartoon.png',
    'build/native-speech-recognizer',
    'sandbox/**/*',
    '!sandbox/*-test-*/**',
    'music/**/*',
    'package.json',
    '!**/*.map',
    '!src/test-*',
    '!src/**/test-*',
    '!scripts/smoke-*.mjs',
    '!src/**/__pycache__/**',
    '!src/**/*.pyc',
    '!**/node_modules/*/{CHANGELOG.md,README.md,readme.md,*.d.ts}',
    '!**/node_modules/.cache',
    '!**/.vscode',
    '!data/**/*',
  ],
  directories: {
    buildResources: 'build',
    output: 'dist',
  },
  afterPack: 'scripts/sign-bundled-binaries.cjs',
  win: {
    icon: 'build/icon.ico',
    target: [{ target: 'nsis', arch: ['x64'] }],
    artifactName: 'OpenVZ-Agent-Setup.${ext}',
    forceCodeSigning: releaseBuild,
    azureSignOptions: azureSignOptions(),
  },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowToChangeInstallationDirectory: true,
    deleteAppDataOnUninstall: false,
    installerHeaderIcon: 'build/installerHeaderIcon.ico',
    installerSidebar: 'build/installerSidebar.bmp',
    uninstallerSidebar: 'build/uninstallerSidebar.bmp',
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: 'OpenVZ Agent',
    include: 'build/installer.nsh',
  },
  mac: {
    icon: 'build/icon.icns',
    target: [
      { target: 'dmg', arch: ['x64', 'arm64'] },
      { target: 'zip', arch: ['x64', 'arm64'] },
    ],
    category: 'public.app-category.productivity',
    minimumSystemVersion: '12.0.0',
    hardenedRuntime: true,
    gatekeeperAssess: false,
    notarize: releaseBuild,
    forceCodeSigning: releaseBuild,
    entitlements: 'build/entitlements.mac.plist',
    entitlementsInherit: 'build/entitlements.mac.inherit.plist',
    artifactName: 'OpenVZ-Agent-mac-${arch}.${ext}',
    extendInfo: {
      NSMicrophoneUsageDescription: 'OpenVZ Agent uses the microphone for voice input and push-to-talk when you enable voice features.',
      NSSpeechRecognitionUsageDescription: 'OpenVZ Agent uses speech recognition only when you enable voice input.',
    },
  },
  publish: [
    {
      provider: 'github',
      owner: 'mrlin728',
      repo: 'openvz-agent',
      releaseType: 'release',
    },
  ],
  generateUpdatesFilesForAllChannels: true,
}
